[package]
name = "reversi-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
rand = "0.8.4"
getopts = "0.2"
rayon = "1.5"
